### ISSUE TITLE
执行agent_post_info.py提示如下错误

### ISSUE THREAD

**Issue by Yangsheng93** [guohongze/adminset#1]
![image](https://cloud.githubusercontent.com/assets/15967300/25084168/acb186d6-238d-11e7-95be-89ef20804215.png)

提示如图错误，从图中可以看出我打印该值，并没有cpu cores对应的值，这是为什么呢？还有该值是获取的物理CPU吗？我测试的环境是虚拟机环境，还请大师指点指点。
![image](https://cloud.githubusercontent.com/assets/15967300/25084303/675f0ddc-238e-11e7-99d8-d8cbc2cce2a5.png)

我该怎么办？请指教。

**Comment by Yangsheng93** [comment]
额额，我的系统大部分都是centos 6,能否优化一下对centos 6系统支持，如果大量的升级python 版本，这确实在生成中比较危险。

**Comment by guohongze** [comment]
报错的图是没有安装dmidecode包，安装一下就好了。
命令 yum install -y dmidecode

你把adminset的服务器安装在centos7.2的版本上，客户机用centos6应该是可以的。具体我找个时间测试一下centos6的客户机，如果agent_post_info.py有不兼容的，我升级一下。

**Comment by Yangsheng93** [comment]
![image](https://cloud.githubusercontent.com/assets/15967300/25091015/43278d06-23b9-11e7-8aa4-7a7fc2719354.png)

我在centos 7上测试是没有问题的，在centos 6上总会遇到一些问题。感觉是不兼容的问题，还请测试完之后回复一下。谢谢

**Comment by guohongze** [comment]
说明：为保证注册IP是管理IP（后续会被ansible等调用），客户端的IP抓取目前使用主机名解析，也就是说主机名必须可以被解析才能执行自动上报脚本，否则报错。 如：主机名为centos6 请在/etc/hosts中加入相应的解析 192.168.x.x centos6，这样再执行agent_post_info.py 可以保证正常运行,脚本本身支持centos6。

**Comment by guohongze** [comment]
centos7上不做解析应该也能拿到IP，但是centos6上必须加入 /etc/hosts解析

**Comment by yubenliu99** [comment]
为什么按你的脚本安装过后静态文件加载不上来

**Comment by guohongze** [comment]
静态文件加载不上来是因为你直接使用了8000端口，你需要使用80端口访问
