### ISSUE TITLE
 打开监控页面报错了

### ISSUE THREAD

**Issue by shenjc2013** [guohongze/adminset#10]
![image](https://user-images.githubusercontent.com/17587107/28007120-bd34cfca-6584-11e7-8bf1-8823e651a991.png)

很不错的东西  我自己也有开发一套运维系统的想法，但是新人好多东西自己写起来特别吃力  目前只写了一个简单的基于ansible的cmdb 希望以后多跟你交流

**Comment by guohongze** [comment]
报错信息是认证错误，应该是mongodb的权限不对导致的，请检查mongodb的用户权限，在系统配置里可以变更。
