### ISSUE TITLE
rsync报错

### ISSUE THREAD

**Issue by AlenJun** [guohongze/adminset#11]
在centos7上，同步报错

**Comment by guohongze** [comment]
截个图

**Comment by AlenJun** [comment]
![image](https://user-images.githubusercontent.com/16571148/28664300-91aaf232-72f2-11e7-872e-773c5f9bef19.png)
error from this.
config:
```
rsync --delete --progress -ra --exclude '.git' $cur_dir/ $adminset_dir
```
rsync $cur_dir ?????

**Comment by guohongze** [comment]
这个是安装脚本中的内容，要直接执行脚本，不要拷贝出来单独执行。

**Comment by guohongze** [comment]
应该是安装脚本的一个路径问题，你下载以后 执行
cd adminset/install
./server_install.sh

**Comment by guohongze** [comment]
已经在v0.5.0中解决此问题。
