### ISSUE TITLE
install失败

### ISSUE THREAD

**Issue by xibls** [guohongze/adminset#12]
用server_install.sh安装的时候, 下了40多个G的内容, 最后磁盘满了才停掉, 不知是怎么回事?

**Comment by guohongze** [comment]
这是一个在虚拟机上安装时的BUG，其实没有那么多内容要下载，具体原因暂时未知，可以现安装一次。
使用Vmware workstation 12.5版本及以上，使用centos7.2.1511版本。

**Comment by xibls** [comment]
目前用vmware 12.5.7 build-5813279版本, centos 7.2还是一样的问题,卡在proc/kcore那里

**Comment by guohongze** [comment]
你怎么执行的安装，是不是没用脚本，直接拷贝脚本中的代码？ 你这40多个G可能是拷贝了系统盘的结果，原因是rsync 带的变量为空，这样导致复制了系统盘的内容

**Comment by guohongze** [comment]
应该是安装脚本的一个路径问题，你下载以后 执行
cd adminset/install
./server_install.sh

**Comment by guohongze** [comment]
已经在v0.5.0中解决此问题。

**Comment by xibls** [comment]
安装过程有交互吗?我调用server_install.sh后显示如下:
`####install depandencies####
do you have a local yum repository?[yes/NO]:yes
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package gcc-4.8.5-11.el7.x86_64 already installed and latest version
No package python-pip available.
No package ansible available.
Package libselinux-python-2.5-6.el7.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package dmidecode.x86_64 1:2.12-9.el7 will be updated
---> Package dmidecode.x86_64 1:3.0-2.1.el7_3 will be an update
---> Package expect.x86_64 0:5.45-14.el7_1 will be installed
--> Processing Dependency: libtcl8.5.so()(64bit) for package: expect-5.45-14.el7_1.x86_64
---> Package python-devel.x86_64 0:2.7.5-48.el7 will be installed
--> Processing Dependency: python(x86-64) = 2.7.5-48.el7 for package: python-devel-2.7.5-48.el7.x86_64
---> Package smartmontools.x86_64 1:6.2-7.el7 will be installed
--> Processing Dependency: mailx for package: 1:smartmontools-6.2-7.el7.x86_64
--> Running transaction check
---> Package mailx.x86_64 0:12.5-12.el7_0 will be installed
---> Package python.x86_64 0:2.7.5-34.el7 will be updated
---> Package python.x86_64 0:2.7.5-48.el7 will be an update
--> Processing Dependency: python-libs(x86-64) = 2.7.5-48.el7 for package: python-2.7.5-48.el7.x86_64
---> Package tcl.x86_64 1:8.5.13-8.el7 will be installed
--> Running transaction check
---> Package python-libs.x86_64 0:2.7.5-34.el7 will be updated
---> Package python-libs.x86_64 0:2.7.5-48.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================================================================================================
 Package                                                             Arch                                                         Version                                                                 Repository                                                     Size
==============================================================================================================================================================================================================================================================================
Installing:
 expect                                                              x86_64                                                       5.45-14.el7_1                                                           base                                                          262 k
 python-devel                                                        x86_64                                                       2.7.5-48.el7                                                            base                                                          393 k
 smartmontools                                                       x86_64                                                       1:6.2-7.el7                                                             base                                                          405 k
Updating:
 dmidecode                                                           x86_64                                                       1:3.0-2.1.el7_3                                                         updates                                                        83 k
Installing for dependencies:
 mailx                                                               x86_64                                                       12.5-12.el7_0                                                           base                                                          244 k
 tcl                                                                 x86_64                                                       1:8.5.13-8.el7                                                          base                                                          1.9 M
Updating for dependencies:
 python                                                              x86_64                                                       2.7.5-48.el7                                                            base                                                           90 k
 python-libs                                                         x86_64                                                       2.7.5-48.el7                                                            base                                                          5.6 M

Transaction Summary
==============================================================================================================================================================================================================================================================================
Install  3 Packages (+2 Dependent packages)
Upgrade  1 Package  (+2 Dependent packages)

Total download size: 9.0 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
(1/8): mailx-12.5-12.el7_0.x86_64.rpm                                                                                                                                                                                                                  | 244 kB  00:00:00     
(2/8): dmidecode-3.0-2.1.el7_3.x86_64.rpm                                                                                                                                                                                                              |  83 kB  00:00:00     
(3/8): expect-5.45-14.el7_1.x86_64.rpm                                                                                                                                                                                                                 | 262 kB  00:00:00     
(4/8): python-2.7.5-48.el7.x86_64.rpm                                                                                                                                                                                                                  |  90 kB  00:00:00     
(5/8): python-devel-2.7.5-48.el7.x86_64.rpm                                                                                                                                                                                                            | 393 kB  00:00:00     
(6/8): smartmontools-6.2-7.el7.x86_64.rpm                                                                                                                                                                                                              | 405 kB  00:00:00     
(7/8): tcl-8.5.13-8.el7.x86_64.rpm                                                                                                                                                                                                                     | 1.9 MB  00:00:00     
(8/8): python-libs-2.7.5-48.el7.x86_64.rpm                                                                                                                                                                                                             | 5.6 MB  00:00:00     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                                          25 MB/s | 9.0 MB  00:00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : python-libs-2.7.5-48.el7.x86_64                                                                                                                                                                                                                           1/11 
  Updating   : python-2.7.5-48.el7.x86_64                                                                                                                                                                                                                                2/11 
  Installing : mailx-12.5-12.el7_0.x86_64                                                                                                                                                                                                                                3/11 
  Installing : 1:tcl-8.5.13-8.el7.x86_64                                                                                                                                                                                                                                 4/11 
  Installing : expect-5.45-14.el7_1.x86_64                                                                                                                                                                                                                               5/11 
  Installing : 1:smartmontools-6.2-7.el7.x86_64                                                                                                                                                                                                                          6/11 
  Installing : python-devel-2.7.5-48.el7.x86_64                                                                                                                                                                                                                          7/11 
  Updating   : 1:dmidecode-3.0-2.1.el7_3.x86_64                                                                                                                                                                                                                          8/11 
  Cleanup    : python-2.7.5-34.el7.x86_64                                                                                                                                                                                                                                9/11 
  Cleanup    : python-libs-2.7.5-34.el7.x86_64                                                                                                                                                                                                                          10/11 
  Cleanup    : 1:dmidecode-2.12-9.el7.x86_64                                                                                                                                                                                                                            11/11 
  Verifying  : 1:tcl-8.5.13-8.el7.x86_64                                                                                                                                                                                                                                 1/11 
  Verifying  : 1:dmidecode-3.0-2.1.el7_3.x86_64                                                                                                                                                                                                                          2/11 
  Verifying  : python-libs-2.7.5-48.el7.x86_64                                                                                                                                                                                                                           3/11 
  Verifying  : expect-5.45-14.el7_1.x86_64                                                                                                                                                                                                                               4/11 
  Verifying  : python-2.7.5-48.el7.x86_64                                                                                                                                                                                                                                5/11 
  Verifying  : mailx-12.5-12.el7_0.x86_64                                                                                                                                                                                                                                6/11 
  Verifying  : 1:smartmontools-6.2-7.el7.x86_64                                                                                                                                                                                                                          7/11 
  Verifying  : python-devel-2.7.5-48.el7.x86_64                                                                                                                                                                                                                          8/11 
  Verifying  : python-libs-2.7.5-34.el7.x86_64                                                                                                                                                                                                                           9/11 
  Verifying  : 1:dmidecode-2.12-9.el7.x86_64                                                                                                                                                                                                                            10/11 
  Verifying  : python-2.7.5-34.el7.x86_64                                                                                                                                                                                                                               11/11 

Installed:
  expect.x86_64 0:5.45-14.el7_1                                                          python-devel.x86_64 0:2.7.5-48.el7                                                          smartmontools.x86_64 1:6.2-7.el7                                                         

Dependency Installed:
  mailx.x86_64 0:12.5-12.el7_0                                                                                                            tcl.x86_64 1:8.5.13-8.el7                                                                                                           

Updated:
  dmidecode.x86_64 1:3.0-2.1.el7_3                                                                                                                                                                                                                                            

Dependency Updated:
  python.x86_64 0:2.7.5-48.el7                                                                                                        python-libs.x86_64 0:2.7.5-48.el7                                                                                                       

Complete!
cp: cannot create regular file ‘/etc/ansible/ansible.cfg’: No such file or directory
`
然后就结束了, 要怎么启动呢?

**Comment by guohongze** [comment]
你的本地YUM源不包含epel的源，所以很多包没有安装上。
do you have a local yum repository?[yes/NO]: 时选择no
或者你在安装之前手工安装一个epel源吧
yum install epel-release
