### ISSUE TITLE
关于adminset相关建议

### ISSUE THREAD

**Issue by Yangsheng93** [guohongze/adminset#2]
测试了一下adminset,体验还不错。简洁明了，使用方便。在使用过程中有几个小小的建议，具体如下：

1. 资产管理，显示数据较少，具体如下图：
![image](https://cloud.githubusercontent.com/assets/15967300/25114293/53ceb69e-2430-11e7-8fa2-7eed780b818c.png)

比如能再增加一些操作系统版本信息、CPU型号、硬盘大小等更好；

2. 增加一下用户的操作记录；

3. 对用户的权限增加做一些说明，比如下图：
![image](https://cloud.githubusercontent.com/assets/15967300/25114708/4367529a-2433-11e7-8556-9e2c9ea3c514.png)

对其中的权限添加的URL始终不解；

暂时只想到这些，非常感谢你的项目；

**Comment by guohongze** [comment]
权限使用说明已经在说0.2版本的明书中提供。
