### ISSUE TITLE
权限管理咨询

### ISSUE THREAD

**Issue by encoding1112** [guohongze/adminset#3]
hi 兄弟 权限管理系统url的使用方式 可以举几个例子说明么

**Comment by encoding1112** [comment]
已经清楚了，配置举例如如下：
权限管理 url配置使用相对 路径。如资产管理 权限URL配置：/cmdb/ 再授权角色，新增用户管理角色，就可以获取该角色url的访问权限

**Comment by guohongze** [comment]
嗯，这个我准备找时间写到使用文档里。

**Comment by Yangsheng93** [comment]
有没有记录CMDB用户操作呢？

**Comment by guohongze** [comment]
CMDB操作记录下次版本更新会加入

**Comment by Yangsheng93** [comment]
好的，谢谢，我会持续关注。
