### ISSUE TITLE
webssh设置了HOSTS解析，但还是不能用，是怎么回事

### ISSUE THREAD

**Issue by Wzongyi** [guohongze/adminset#35]

**Comment by guohongze** [comment]
没有开启服务吧 在系统中保证服务已经开户 service webssh start

**Comment by bbotte** [comment]
需要内网dns的，比如
adminset.conf
    [webssh]
    domain = test.com

内网需要把所有客户端主机都能dns解析，比如
    host1 的/etc/hosts:  host1 192.168.1.5

ping host1.test.com 就是 192.168.1.5 这台主机，这样才能打开webssh

**Comment by guohongze** [comment]
v0.40新版本无需设置解析
