### ISSUE TITLE
是否考虑集成LDAP统一账号认证

### ISSUE THREAD

**Issue by weiguang1017** [guohongze/adminset#36]
今天下载项目安装了下，感觉非常简洁实用，另外是否能实现如下需求：
1.默认首页是否直接展示后台设置的网站导航呢？
2.能不能增加LDAP统一账号认证；
3.暂时还未正式使用，希望后面熟悉后一起加入到开发队伍。。。

**Comment by guohongze** [comment]
将来会整合

**Comment by weiguang1017** [comment]
方便留个联系方式吗

**Comment by guohongze** [comment]
13301163735 可以加我微信




guohongze@126.com

发件人： weiguang1017
发送时间： 2018-01-02 11:33
收件人： guohongze/adminset
抄送： guohongze; Comment
主题： Re: [guohongze/adminset] 是否考虑集成LDAP统一账号认证 (#36)
方便留个联系方式吗

**Comment by guohongze** [comment]
0.30已上线LDAP
