### ISSUE TITLE
执行安装脚本报错server_install.sh, 公司云服务器上VPN

### ISSUE THREAD

**Issue by wxj19880511** [guohongze/adminset#38]
Install fail! RequestError: socket hang up (req "error"), GET http://registry.npm.taobao.org/socket.io -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":51,"createSocketErrorCount":0,"closeSocketCount":42,"errorSocketCount":0,"timeoutSocketCount":41,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:80:":9},"requests":{}})
headers: {}

**Comment by guohongze** [comment]
连接不上阿里云的NPM源，这个是网络问题。
