### ISSUE TITLE
关于分页这边的疑问

### ISSUE THREAD

**Issue by wayne-77** [guohongze/adminset#4]
![image](https://cloud.githubusercontent.com/assets/21037074/25833260/79e71d62-34a2-11e7-9ef9-57ebcc832955.png)
你好，请问这边的分页部分最多只能显示20条？

**Comment by guohongze** [comment]
这是个BUG，等我处理一下。

**Comment by guohongze** [comment]
bug已修复，请更新一下代码即可。

**Comment by wayne-77** [comment]
嗯嗯 谢谢响应 ， 不过这个bug我也算是暂时解决了。看了你更新的代码发现解决方法跟你是一样的。
