### ISSUE TITLE
脚本提示安装成功了，但是访问报302呢

### ISSUE THREAD

**Issue by wenchangming211** [guohongze/adminset#43]
##############install finished###################
Restarting redis (via systemctl):                          [  确定  ]
Redirecting to /bin/systemctl restart  mariadb.service
Redirecting to /bin/systemctl restart  adminset.service
Redirecting to /bin/systemctl restart  celery.service
Redirecting to /bin/systemctl restart  beat.service
Redirecting to /bin/systemctl restart  mongod.service
Redirecting to /bin/systemctl restart  sshd.service
Redirecting to /bin/systemctl restart  webssh.service
please access website http://server_ip
you have installed adminset successfully!!!
################################################

[root@SZC-l201872 server]# curl -i http://localhost:80
HTTP/1.1 302 Found
Server: nginx/1.12.2
Date: Mon, 26 Feb 2018 11:00:32 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
Location: /navi/

**Comment by guohongze** [comment]
HTTP/1.1 302 Found
使用浏览器打开，不要用curl
