### ISSUE TITLE
开发环境在ubuntu上面吗？ 

### ISSUE THREAD

**Issue by louiszu** [guohongze/adminset#45]
还是在windows上面开发的？ 在centos上安装好了，不好调试代码。

**Comment by louiszu** [comment]
你的开发调试环境是怎么样的

**Comment by louiszu** [comment]
开发环境
centos 7.2(1511) django 1.11.9（兼容Django1.9.x） python 2.7     是用的pycharm 吗？

**Comment by guohongze** [comment]
是pycharm
