### ISSUE TITLE
Server 端运行auto_install.sh 执行到/usr/bin/npm install forever -g 报错

### ISSUE THREAD

**Issue by idandan0346** [guohongze/adminset#50]
执行/usr/bin/npm install forever -g的时候报错，感觉是源不可用。
<img width="798" alt="image" src="https://user-images.githubusercontent.com/23513915/38286718-5a139500-37f9-11e8-865a-473dedbd9554.png">
有什么解决的建议吗？

**Comment by idandan0346** [comment]
执行了一下npm install -g cnpm --registry=https://registry.npm.taobao.org
可以继续了。

**Comment by guohongze** [comment]
问题6：自动或手动安装时安装失败。
原因：外部资源无法下载
解决方法：
请确认yum、pypi、npm等资源可用
如果node 编译时NPM包卡住，请在安装脚本autho_install.sh的47-49行，或server_install.sh的75-77行替换成如下代码
/usr/bin/npm install -g cnpm --registry=https://registry.npm.taobao.org
/usr/bin/cnpm install --production
/usr/bin/cnpm install forever -g
