### ISSUE TITLE
对python3.6的支持不是很理想

### ISSUE THREAD

**Issue by bopo** [guohongze/adminset#53]
对python3.6的支持不是很理想，我fork了一个版本，做了下python3.6的修改。
另外，我建议出一个docker部署的版本。如果，作者比较忙，没时间，我可以帮忙做docker化。
可以联系我。

**Comment by guohongze** [comment]
3.6还有两包的名字有点问题，其它应该都OK了

**Comment by guohongze** [comment]
可以提过来吧
