### ISSUE TITLE
无法创建普通文件"/usr/lib/systemd/system/webssh.service": 没有那个文件或目录

### ISSUE THREAD

**Issue by pyxin** [guohongze/adminset#55]
创建文件夹 重复执行 还是报错

npm http 200 http://registry.cnpmjs.org/cycle
/usr/local/bin/forever -> /usr/local/lib/node_modules/forever/bin/forever
forever@0.15.3 /usr/local/lib/node_modules/forever
├── object-assign@3.0.0
├── path-is-absolute@1.0.1
├── clone@1.0.4
├── colors@0.6.2
├── timespan@2.3.0
├── cliff@0.1.10 (eyes@0.1.8, colors@1.0.3)
├── prettyjson@1.2.1 (minimist@1.2.0, colors@1.2.1)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── winston@0.8.3 (cycle@1.0.3, async@0.2.10, stack-trace@0.0.10, eyes@0.1.8, isstream@0.1.2, pkginfo@0.3.1)
├── nconf@0.6.9 (ini@1.3.5, async@0.2.9, optimist@0.6.0)
├── shush@1.0.0 (strip-json-comments@0.1.3, caller@0.0.1)
├── utile@0.2.1 (async@0.2.10, deep-equal@1.0.1, ncp@0.4.2, i@0.3.6, mkdirp@0.5.1, rimraf@2.6.2)
├── nssocket@0.5.3 (lazy@1.0.11, eventemitter2@0.4.14)
├── forever-monitor@1.7.1 (ps-tree@0.0.3, minimatch@3.0.4, chokidar@1.7.0, broadway@0.3.6)
└── flatiron@0.4.3 (director@1.2.7, optimist@0.6.0, prompt@0.2.14, broadway@0.3.6)
sending incremental file list

sent 68421 bytes  received 539 bytes  137920.00 bytes/sec
total size is 31514339  speedup is 456.99
adminset/install/server/auto_install.sh: line 63: systemctl: command not found

**Comment by guohongze** [comment]
服务器用的什么操作系统？
adminset要求是centos7

**Comment by pyxin** [comment]
好吧没注意到  我的是6.9
