### ISSUE TITLE
猎头刘康 可以发我你的简历么？

### ISSUE THREAD

**Issue by superliukang** [guohongze/adminset#60]
18588511446 方便跟您电话聊聊么？

**Comment by uhe1231** [comment]
现在猎头也上github了, 厉害咯!!

**Comment by net592** [comment]
6666 厉害了

**Comment by superliukang** [comment]
聊聊嘛

**Comment by chpiter** [comment]
厉害厉害 佩服佩服

**Comment by liangSir666** [comment]
|
姓名黄建亮
13716127913@163.com
公司名称：北京北大软件工程股份有限公司
地址：北京市海淀区北四环西路中关村国际创新大厦1102
手机：13716127913
|

扫描该二维码，可以将电子名片迅速保存到手机 使用帮助

|

在 2018-06-27 14:53:02，"chpiter" <notifications@github.com> 写道：


厉害厉害 佩服佩服
