### ISSUE TITLE
关于django-celery-beat的问题

### ISSUE THREAD

**Issue by caiqing0204** [guohongze/adminset#67]
我看网上很多博客都说过，celery4.x以后，使用的django-celery-beat,做任务的调度，当修改任务以后，如果不重启beat，任务还是调度以前的任务，修改后的任务没有办法执行，请问您，您这里是如何解决这一个问题的？谢谢您，麻烦看到后，帮忙解答一下。

**Comment by guohongze** [comment]
4.2版本解决了这个BUG
