### ISSUE TITLE
对用户权限提个建议

### ISSUE THREAD

**Issue by net881004** [guohongze/adminset#68]
比如给一个帐号设置成只能查看监控菜单后，能否实现这个帐号登录后只显示监控菜单呢，即其它菜单不要显示出来，虽然它们提示没有权限访问。
谢谢您这个优秀的平台，请问3版本什么时候发布呢？

**Comment by guohongze** [comment]
细节上的优化，有这个打算，

**Comment by guohongze** [comment]
v0.31 已经支持左边栏菜单用户权限展示
