### ISSUE TITLE
安装问题请教

### ISSUE THREAD

**Issue by lyhabc** [guohongze/adminset#76]
安装的时候，请问这个问题怎么解决
      Successfully uninstalled pyasn1-0.1.9
  Running setup.py install for python-ldap ... done
  Running setup.py install for psutil ... done
  Found existing installation: requests 2.6.0
Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by guohongze** [comment]
你有包依赖之前安装的requests导致

在安装之前执行一次
pip install --ignore-installed requests==2.11.1

**Comment by lyhabc** [comment]
可以了
