### ISSUE TITLE
返回数据对象而不是数据

### ISSUE THREAD

**Issue by xiang5** [guohongze/adminset#78]
![image](https://user-images.githubusercontent.com/19387573/48135752-be667880-e2d8-11e8-84e3-d4eefe4c4d36.png)

![image](https://user-images.githubusercontent.com/19387573/48135843-0f766c80-e2d9-11e8-9bfa-ef2d9829a728.png)

改成python3,mysql之后
所有外键返回的都是对象，而不是实际的数据
请介绍下这个bug的原理及修复方法（目前在静态页面上修改了几个明显的，其他的都没修改）

**Comment by guohongze** [comment]
我只是让语法兼容了PY3，但开发和生产环境都是2呀。你要用PY3，可以研究一下，把结果贴出来。

**Comment by xiang5** [comment]
换成python3，一些小地方修改下即可，主要的问题是form模板返回外键都是对象类型。
给你的126邮箱发邮件发不进去，能提供下方便的联系方式吗？

**Comment by xiang5** [comment]
> 
> 
> 换成python3，一些小地方修改下即可，主要的问题是form模板返回外键都是对象类型。
> 给你的126邮箱发邮件发不进去，能提供下方便的联系方式

**Comment by xiang5** [comment]
换成python3，一些小地方修改下即可，主要的问题是form模板返回外键都是对象类型。
给你的126邮箱发邮件发不进去，能提供下方便的联系方式吗？

我的qq：1299785499
微信：17051015890

**Comment by xiang5** [comment]
应该不是这个原因，请帮忙看下
https://github.com/xiang5/adminset-py3.git

daemon：    
http://47.88.218.151 
账号：admin 
密码：duduadmin
