### ISSUE TITLE
自动安装失败

### ISSUE THREAD

**Issue by BensonMax** [guohongze/adminset#84]
Transaction check error:
  file /usr/include/mysql/client_plugin.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_64 conge bt-mysql-5.5.57-1.el7.centos.x86_64
  file /usr/include/mysql/plugin.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_64 conflicts ysql-5.5.57-1.el7.centos.x86_64
  file /usr/include/mysql/plugin_audit.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_64 confe bt-mysql-5.5.57-1.el7.centos.x86_64
  file /usr/include/mysql/plugin_auth.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_64 confl bt-mysql-5.5.57-1.el7.centos.x86_64
  file /usr/include/mysql/plugin_auth_common.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_6package bt-mysql-5.5.57-1.el7.centos.x86_64
  file /usr/include/mysql/plugin_ftparser.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_64 ckage bt-mysql-5.5.57-1.el7.centos.x86_64
  file /usr/include/mysql/psi/mysql_file.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_64 coage bt-mysql-5.5.57-1.el7.centos.x86_64
  file /usr/include/mysql/psi/mysql_thread.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_64 ckage bt-mysql-5.5.57-1.el7.centos.x86_64
  file /usr/include/mysql/service_my_snprintf.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_ package bt-mysql-5.5.57-1.el7.centos.x86_64
  file /usr/include/mysql/services.h from install of mariadb-devel-1:5.5.60-1.el7_5.x86_64 conflict-mysql-5.5.57-1.el7.centos.x86_64

**Comment by guohongze** [comment]
数据库冲突吧，找一个干净的系统，或使用 minimal版本的centos
