### ISSUE TITLE
命令注入

### ISSUE THREAD

**Issue by 360CodeSafe** [guohongze/adminset#87]
您好，我是奇虎360代码卫士团队的工作人员，在我们的开源项目检测中发现adminset存在命令注入风险，详细信息如下：
在setup/ansible.py中
![image](https://user-images.githubusercontent.com/39950310/50545387-a7dffc00-0c4d-11e9-8334-e4da814f812b.png)
![image](https://user-images.githubusercontent.com/39950310/50545385-9860b300-0c4d-11e9-9702-f3888803766f.png)
没有对pbook进行校验或限制，容易造成命令注入，并且subprocess.Popend方法中不建议设置shell=True
由于我对adminset不熟悉，希望你可以看一下

**Comment by guohongze** [comment]
Pbook接收POST传递来的是文件名，如果有恶意攻击者注入命令会被当做文件名来处理，调用的是ansible-playbook 这个命令，这个命令会把参数当做文件名来对待去寻找相应文件，而不是直接执行一个shell命令，事实上无法形成注入。
