### ISSUE TITLE
0.50 版本安装后访问报错

### ISSUE THREAD

**Issue by longbinma** [guohongze/adminset#92]
![image](https://user-images.githubusercontent.com/16474596/52680914-1d412b00-2f75-11e9-9283-66311cf102d2.png)

**Comment by guohongze** [comment]
找一个干净的centos7系统，不要使用原来的系统。

**Comment by longbinma** [comment]
找了干净的系统，自动安装的方式装的，报这个错
![image](https://user-images.githubusercontent.com/16474596/52690379-6ce51e00-2f98-11e9-87de-de2fd139ef2c.png)

**Comment by guohongze** [comment]
在服务器上执行
pip install -U django==1.11.18
这是github一个误报导致的版本不兼容fuck!

**Comment by longbinma** [comment]
可以了，谢谢！
