### ISSUE TITLE
普通用户无法查看监控

### ISSUE THREAD

**Issue by DaRingLee** [guohongze/adminset#99]
![image](https://user-images.githubusercontent.com/12238072/53803979-3f7d0600-3f81-11e9-8b4b-3e5c8614a023.png)

如图所示，test无法查看监控信息

**Comment by guohongze** [comment]
需要对创建权限url并对用户进行相应授权
/monitor/getcpu/
/monitor/getmem/
/monitor/getdisk/
/monitor/getnet/

**Comment by DaRingLee** [comment]
> 需要创建权限url并对用户进行相应授权
> /monitor/getcpu/
> /monitor/getmem/
> /monitor/getdisk/
> /monitor/getnet/
